# -*- coding: utf-8 -*-
"""oasis infobyte2(ds).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15sclRCHG9pIj5zGCnlVP8xL8RT0wkQAM
"""



import pandas as pd
import matplotlib.pyplot as plt

data = {
    'Date': ['2020-01-01', '2020-02-01', '2020-03-01', '2020-04-01', '2020-05-01'],
    'Unemployment_Rate': [4.3, 4.4, 14.7, 20.0, 13.3],
}
data

df = pd.DataFrame(data)
df

plt.figure(figsize=(10, 6))
plt.plot(df['Date'], df['Unemployment_Rate'], marker='o')
plt.title('Unemployment Rate During COVID-19')
plt.xlabel('Date')
plt.ylabel('Unemployment Rate (%)')
plt.xticks(rotation=45)
plt.grid(True)
plt.show()