# -*- coding: utf-8 -*-
"""oasis4(ds).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sNSMZ4ImBOTDGokonZHlICvgmYqSRp6x
"""

import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report

emails = [
    ("cryptic messages", "spam"),
    ("scams", "ham"),
    ("most dangerously", "spam"),
    ("phishing content", "ham"),
    ]
emails

X = [email[0] for email in emails]
y = [email[1] for email in emails]
X
y

tfidf_vectorizer = TfidfVectorizer()
X_tfidf = tfidf_vectorizer.fit_transform(X)
tfidf_vectorizer

X_train, X_test, y_train, y_test = train_test_split(X_tfidf, y, test_size=0.2, random_state=42)
X_train
X_test
y_train
y_test

nb_classifier = MultinomialNB()
nb_classifier

nb_classifier.fit(X_train, y_train)
y_pred = nb_classifier.predict(X_test)
y_pred

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)
print(classification_report(y_test, y_pred))